### ISSUE TITLE
Delete-able span labels

### ISSUE THREAD

**Issue by herongrove** [lum-ai/TAG#16]
As a user, I want to be able to delete existing span labels by
1. single-clicking the span
2. pressing `Delete` or `Backspace`

The change should be reflected in the parsed data.

**Comment by flaviuGC** [comment]
Single-click the span now selects the item.
Double click the span now edits the item.

In single-click, the span can be deleted with the DELETE, BACKSPACE button.
in double click, the span can be deleted with CTRL + DELETE or CTRL + BACKSPACE (or as previously by deleting the entire text)
